{% set name = "zola" %}
{% set version = "0.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/getzola/zola/archive/v{{ version }}.tar.gz
  sha256: bae10101b4afff203f781702deeb0a60d3ab0c9f0c7a616a7c1e0c504c33c93f

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - oniguruma
    - openssl

test:
  commands:
    - zola --help

about:
  home: https://github.com/getzola/zola
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A fast static site generator in a single binary with everything built-in.
  dev_url: https://github.com/getzola/zola

extra:
  recipe-maintainers:
    - danielnachun
