context:
  version: "0.19.2"

package:
  name: zola
  version: ${{ version }}

source:
  url: https://github.com/getzola/zola/archive/v${{ version }}.tar.gz
  sha256: bae10101b4afff203f781702deeb0a60d3ab0c9f0c7a616a7c1e0c504c33c93f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - oniguruma
    - openssl

tests:
  - script:
      - zola --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A fast static site generator in a single binary with everything built-in.
  homepage: https://github.com/getzola/zola
  repository: https://github.com/getzola/zola

extra:
  recipe-maintainers:
    - danielnachun
